In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 15 14:49:19 2019

@author: krish.naik
"""

# Face Recognition

# Importing the libraries
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np
import mtcnn

from keras.preprocessing import image
model = load_model('facefeatures_aug_model.h5')
face_detector = mtcnn.MTCNN()

def face_extractor(img):
    
    frame_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = face_detector.detect_faces(frame_rgb)
    
    if results is ():
        return None
    
    for res in results:
        x1, y1, width, height = res['box']
        x1, y1 = abs(x1), abs(y1)
        x2, y2 = x1+width, y1+height
        cv2.rectangle(img, (x1, y1), (x2, y2), (255, 0, 0), thickness=2)
        cropped_face = img[y1:y2, x1:x2]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][2]>0.2):
            name='Arpan'
        elif (pred[0][1]>0.2):
            name='Archana'
        elif (pred[0][0]>0.2):
            name='Akhil'
        elif (pred[0][3]>0.2):
            name='Jayeeta'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

       



[[0.0000000e+00 1.2018960e-03 9.7261091e-37 9.9879813e-01]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.1075233e-24]]
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
[[0.000000e+00 1.000000e+00 0.000000e+00 1.741589e-38]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 3.9104116e-17]]
[[0.00000e+00 1.00000e+00 0.00000e+00 2.52665e-13]]
[[0.000000e+00 1.000000e+00 0.000000e+00 5.835846e-22]]
[[0. 1. 0. 0.]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 4.0322883e-09]]
[[0.000000e+00 1.000000e+00 0.000000e+00 3.322115e-26]]
[[0.00000e+00 1.00000e+00 0.00000e+00 7.50481e-24]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 6.3185427e-19]]
[[0.000000e+00 1.000000e+00 0.000000e+00 9.034383e-24]]
[[0.000000e+00 1.000000e+00 0.000000e+00 5.132457e-25]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 5.6689066e-31]]
[[0.00000e+00 1.00000e+00 0.00000e+00 5.46078e-19]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 3.3501742e-20]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.4449148e-21]]
[[0.0000000e+00 1.0000000e+00 0.0000

[[0.0000000e+00 5.4767252e-24 0.0000000e+00 1.0000000e+00]]
[[0.0000000e+00 1.3709814e-34 0.0000000e+00 1.0000000e+00]]
[[0.0000000e+00 3.3834598e-15 1.3945002e-35 1.0000000e+00]]
[[0.0000000e+00 5.4058073e-14 0.0000000e+00 1.0000000e+00]]
[[0.0000000e+00 1.4039795e-28 0.0000000e+00 1.0000000e+00]]
[[0.0000000e+00 6.2860936e-13 0.0000000e+00 1.0000000e+00]]
[[0.000000e+00 1.000000e+00 0.000000e+00 3.033151e-11]]
